package: multinewsletter
version: '3.0.0'
author: Tobias Krais
supportpage: http://www.redaxo.org/de/forum/addons-packages-f43/fragen-zu-multinewsletter-in-redaxo-5-t21075.html

page:
    title: MultiNewsletter
    perm: multinewsletter[]
    icon: rex-icon rex-icon-envelope
    subpages:
        newsletter: { title: 'translate:multinewsletter_menu_versand' }
        user: { title: 'translate:multinewsletter_menu_user' }
        groups: { title: 'translate:multinewsletter_menu_groups' }
        config: { title: 'translate:multinewsletter_menu_config' }
        archive: { title: 'translate:multinewsletter_menu_archive' }
        help: { title: 'translate:multinewsletter_menu_help' }
        import: { title: 'translate:multinewsletter_menu_import' }

requires:
    redaxo: '>=5.1.0'
    php:
        version: '>=5.3'
    packages:
        phpmailer: '>=2.0.1'