package: multinewsletter
version: '3.0.5'
author: Tobias Krais
supportpage: http://www.redaxo.org/de/forum/addons-packages-f43/fragen-zu-multinewsletter-in-redaxo-5-t21075.html

page:
    title: MultiNewsletter
    perm: multinewsletter[]
    icon: rex-icon rex-icon-envelope
    subpages:
        newsletter: { title: 'translate:multinewsletter_menu_versand', icon: rex-icon rex-icon-envelope }
        user: { title: 'translate:multinewsletter_menu_user', icon: rex-icon rex-icon-user }
        groups: { title: 'translate:multinewsletter_menu_groups', icon: rex-icon rex-icon-category }
        config: { title: 'translate:multinewsletter_menu_config', icon: rex-icon rex-icon-system }
        archive: { title: 'translate:multinewsletter_menu_archive', icon: rex-icon rex-icon-backup }
        help: { title: 'translate:multinewsletter_menu_help', icon: rex-icon rex-icon-help }
        import: { title: 'translate:multinewsletter_menu_import', icon: rex-icon rex-icon-import }

requires:
    redaxo: '>=5.1.0'
    php:
        version: '>=5.3'
    packages:
        phpmailer: '>=2.0.1'