package: multinewsletter
version: '3.5.1'
author: Tobias Krais
supportpage: https://github.com/TobiasKrais/multinewsletter/issues/

page:
    title: MultiNewsletter
    perm: 'multinewsletter[]'
    icon: rex-icon rex-icon-envelope
    subpages:
        newsletter: { title: 'translate:multinewsletter_menu_versand', icon: rex-icon rex-icon-envelope }
        user: { title: 'translate:multinewsletter_menu_user', icon: rex-icon rex-icon-user }
        groups: { title: 'translate:multinewsletter_menu_groups', icon: rex-icon rex-icon-category }
        archive: { title: 'translate:multinewsletter_menu_archive', icon: rex-icon rex-icon-backup }
        settings:
            icon: rex-icon rex-icon-system
            title: 'translate:multinewsletter_menu_config'
            itemclass: pull-right
            subpages:
                settings: { title: 'translate:multinewsletter_menu_config', icon: rex-icon rex-icon-system }
                export: { title: 'translate:multinewsletter_config_settings_export_long', icon: rex-icon fa-upload }
                import: { title: 'translate:multinewsletter_config_settings_import_long', icon: rex-icon fa-download }
        help:
            icon: rex-icon rex-icon-help
            title: 'translate:multinewsletter_menu_help'
            itemclass: pull-right
            subpages:
                import: { title: 'translate:multinewsletter_help_chapter_import', icon: rex-icon fa-download }
                versand: { title: 'translate:multinewsletter_help_chapter_versand', icon: rex-icon fa-send}
                faq: { title: 'translate:multinewsletter_help_chapter_faq', icon: rex-icon fa-question-circle}
                module: { title: 'translate:multinewsletter_help_chapter_module', icon: rex-icon rex-icon-module}
                templates: { title: 'translate:multinewsletter_help_chapter_template', icon: rex-icon rex-icon-template }
                updatehinweise: { title: 'translate:multinewsletter_help_chapter_updatehinweise', icon: rex-icon rex-icon-install }
                changelog: { title: 'translate:multinewsletter_help_chapter_changelog', icon: rex-icon fa-list-alt}

requires:
    redaxo: '>=5.10.0'
    packages:
        d2u_helper: '>=1.5.6'
        phpmailer: '>=2.0.1'

default_config:
    sender: ''
    link: '0'
    link_abmeldung: '0'
    max_mails: '15'
    versandschritte_nacheinander: '20'
    sekunden_pause: '305'
    lang_fallback: '1'
    default_test_anrede: '0'
    default_test_vorname: 'Max'
    default_test_nachname: 'Mustermann'
    subscribe_meldung_email: ''
    
installer_ignore:
    - .github
